# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_gen/controller.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19grpc_gen/controller.proto\x12\ncontroller\",\n\x17PressedCharacterRequest\x12\x11\n\tcharacter\x18\x01 \x01(\t\"\x1a\n\x18PressedCharacterResponse\"$\n\x15PressedSpecialRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"\x18\n\x16PressedSpecialResponse2\xc8\x01\n\nController\x12_\n\x10PressedCharacter\x12#.controller.PressedCharacterRequest\x1a$.controller.PressedCharacterResponse\"\x00\x12Y\n\x0ePressedSpecial\x12!.controller.PressedSpecialRequest\x1a\".controller.PressedSpecialResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_gen.controller_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PRESSEDCHARACTERREQUEST']._serialized_start=41
  _globals['_PRESSEDCHARACTERREQUEST']._serialized_end=85
  _globals['_PRESSEDCHARACTERRESPONSE']._serialized_start=87
  _globals['_PRESSEDCHARACTERRESPONSE']._serialized_end=113
  _globals['_PRESSEDSPECIALREQUEST']._serialized_start=115
  _globals['_PRESSEDSPECIALREQUEST']._serialized_end=151
  _globals['_PRESSEDSPECIALRESPONSE']._serialized_start=153
  _globals['_PRESSEDSPECIALRESPONSE']._serialized_end=177
  _globals['_CONTROLLER']._serialized_start=180
  _globals['_CONTROLLER']._serialized_end=380
# @@protoc_insertion_point(module_scope)
